from turtle import * 
def sanjiao():
    for _ in range(5):
        forward(30)
        left(72)
        forward(30)
        rt(144)
def canvas():
    setup(0.9,0.9)
    penup()
    goto(-250,150)
    pendown()
    color("red","red")
    begin_fill()
    forward(500)
    rt(90)
    forward(300)
    rt(90)
    forward(500)
    rt(90)
    forward(300)
    end_fill()
def small_star():
    for _ in range(5):
        forward(10)
        left(72)
        forward(10)
        rt(144)
def draw():
    hideturtle()
    canvas()
    penup()
    home()
    goto(-200,75)
    pendown()
    color("yellow","yellow")
    begin_fill()
    sanjiao()
    end_fill()

    penup()
    home()
    rt(36)
    goto(-120,120)
    pendown()
    color("yellow","yellow")
    begin_fill()
    small_star()
    end_fill()
    penup()
    home()
    left(36)
    goto(-80,75)
    pendown()
    begin_fill()
    small_star()
    end_fill()
    penup()
    home()
    
    goto(-80,30)
    pendown()
    color("yellow","yellow")
    begin_fill()
    small_star()
    end_fill()
    penup()
    home()
    rt(36)
    goto(-120,0)
    pendown()
    color("yellow","yellow")
    begin_fill()
    small_star()
    end_fill()
    mainloop()

    
draw()
