import turtle,time
# turtle.home()
# help(turtle)
# turtle.forward(50)
# turtle.circle(5,180,6)
# turtle.backward(-50)
# time.sleep(1)
# while 1:
    # turtle.forward(50)
    # turtle.rt(144)
    # turtle.forward(50)
    # turtle.rt(144)
    # turtle.forward(50)
    # turtle.rt(144)
    # turtle.forward(50)
    # turtle.rt(144)
    # turtle.forward(50)
    # turtle.rt(144)
    # turtle.forward(50)
    # turtle.rt(144)
    # turtle.forward(50)
    # turtle.circle(40,None,5)
turtle.dot(5,"red")
turtle.fd(50)